services:
  frontend:
    image: spa-app
    init: true
    pull_policy: never
    container_name: spa-app_c
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
