name: Junit - Unit & Integration Tests

on:
  push:
    branches: [main, master]
    paths:
      - "src/**/*"
      - "__tests__/unit/**/*"
      - "__tests__/integration/**/*"
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test
